l# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [26]:
import numpy as np

In [27]:
np.random.randint(0, 20, size = (4, 7))

array([[ 2,  9,  4,  0,  3, 19, 19],
       [11,  7, 19, 10, 18, 13,  1],
       [15, 15,  4, 15, 11,  2,  9],
       [ 4, 15, 15, 17,  2,  0, 14]])

In [28]:
data = np.random.uniform(0, 20, size = (4, 7))
print(data)
(data-np.min(data))/(np.max(data)-np.min(data))

[[9.28215895e+00 1.14234746e+01 3.06970298e+00 2.78924964e+00
  5.43706452e+00 7.03146801e-01 3.35953093e+00]
 [6.85922798e+00 1.63476772e+01 9.77483712e+00 1.03834963e+01
  9.97449307e+00 3.15586021e+00 1.93984132e+01]
 [1.41598454e+01 1.13776228e-02 1.30851369e+01 1.22179749e+01
  1.51648185e+01 5.32226974e+00 1.65161911e+01]
 [1.57625490e+01 1.51317904e+01 1.32611738e+00 1.53042176e+01
  2.93712699e+00 9.41692790e+00 1.64794594e+01]]


array([[0.47819489, 0.5886458 , 0.15775106, 0.14328503, 0.2798616 ,
        0.03568205, 0.17270063],
       [0.35321802, 0.84264041, 0.50360765, 0.53500282, 0.51390608,
        0.16219512, 1.        ],
       [0.72979016, 0.        , 0.67435577, 0.62962681, 0.78162754,
        0.27394039, 0.8513325 ],
       [0.81245899, 0.77992392, 0.06781541, 0.78881786, 0.15091267,
        0.48514639, 0.84943785]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [29]:
np.random.randint(0, 10, size = (8, 10))

array([[5, 6, 2, 0, 9, 4, 5, 3, 7, 2],
       [1, 4, 8, 9, 4, 4, 8, 3, 9, 7],
       [6, 9, 2, 2, 3, 5, 7, 1, 0, 4],
       [4, 8, 5, 7, 3, 5, 6, 9, 3, 6],
       [2, 8, 1, 0, 8, 5, 2, 3, 4, 2],
       [4, 5, 4, 3, 1, 1, 2, 8, 6, 6],
       [8, 8, 5, 2, 6, 4, 9, 1, 4, 1],
       [9, 5, 5, 5, 7, 5, 1, 9, 9, 4]])

In [30]:
arr = np.random.randint(0, 10, size = (8, 10))
print(arr)
print("Row Index",np.argmin(np.sum(arr, axis=1)))
arr[np.argmin(np.sum(arr, axis=1))]

[[8 1 8 5 5 4 8 8 2 9]
 [3 0 5 8 6 9 1 3 0 4]
 [4 3 6 8 8 6 9 0 5 3]
 [3 2 0 2 7 2 5 9 7 5]
 [2 1 8 0 7 8 6 4 6 5]
 [7 6 6 7 2 2 3 1 0 5]
 [7 1 8 4 6 7 8 4 0 2]
 [0 6 5 1 2 1 7 3 2 3]]
Row Index 7


array([0, 6, 5, 1, 2, 1, 7, 3, 2, 3])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [31]:
point_1 = np.random.randint(0, 20, size=5)
point_2 = np.random.randint(0, 20, size=5)
print(point_1)
print(point_2)
#first way
square = np.square(point_1 - point_2)
sum_square = np.sum(square)
print(np.sqrt(sum_square))
#second way
distance = np.linalg.norm(point_1-point_2)
print(distance)

[ 1  9 18  7  4]
[ 9 18 12 12 18]
20.049937655763422
20.049937655763422


In [32]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [39]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
#решение: x = a^-1*(-c)*b^-1

x0 = np.matmul(np.linalg.inv(a),(-c))
print(x0)
x =  np.matmul(x0,np.linalg.inv(b))
print(x)

[[ 3. -1.]
 [-4.  3.]
 [ 1. -7.]]
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

/content/sample_data/minutes_n_ingredients.csv

In [40]:
data = np.loadtxt("/content/drive/MyDrive/L/minutes_n_ingredients.csv", delimiter=',', skiprows=1, dtype=np.int32)
# first 5 rows
print(data[0:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [35]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [41]:
d1 = data.copy()

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [46]:
#делаем срез массива, извлекаем все кроме первого массива
sliced = data[:,1:]
# находим среднее по столбцам среза
print(np.mean(sliced,axis=0))
# находим минимум по столбцам среза
print(np.min(sliced, axis=0))
# находим максимум по столбцам среза
print(np.max(sliced, axis=0))
# находим медиану по столбцам среза
print(np.median(sliced, axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [47]:
np.clip(data[:, 1],0,np.quantile(data[:, 1],0.75,method='higher'))

array([60, 25, 10, ..., 65,  5, 65], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [48]:
print(np.count_nonzero (d1[:, 1] == 0))

479


In [49]:
np.place(data, data==0, 1)

In [50]:
#Проверка
print(np.count_nonzero (data[:, 1] == 1)-(np.count_nonzero (d1[:, 1] == 1)))

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [51]:
#уникальные рецепты - это рецепты, у которых не повторяются минуты и количество ингредиентов
len(np.unique(sliced, axis=0))

4183

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [52]:
print(np.unique(data[:, 2], axis=0))
print(np.unique(data[:, 2], axis=0).size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [53]:
data2 = data[np.where(data[:, 2] <= 5)]
print(data2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [54]:
A = data[:, 1]
B = data[:, 2]
C = B/A
print(C)
data_c = [C]
sliced = data_c[:]
print(np.max(sliced,axis=1))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
[24.]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей
продолжительностью

In [55]:
d1_sorted_desc = d1[d1[:, 1]. argsort ()[::-1]]
print(d1_sorted_desc)

[[    261647 2147483647          8]
 [    216215     259260          7]
 [    425681     259205          2]
 ...
 [     50748          0         12]
 [      5354          0          8]
 [      4896          0         14]]


In [56]:
x = np.mean(d1_sorted_desc[:100,2], axis=0)
#print(np.mean(d1_sorted_desc[2],axis=0))
x

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [68]:
index = np.random.randint(d1.shape[0], size=10)
random_rows = d1[index, :]
print(random_rows)

[[202693     10     13]
 [381300     20      4]
 [182729     10      5]
 [100462    110     12]
 [425697     85     12]
 [407657     30     10]
 [501171      5     10]
 [377952     85     11]
 [448787     40     15]
 [432509     60     15]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [210]:
sr1 =  data[:,2:]
r = np.mean(sr1,axis=0)
print(r) # cреднее значение инградиентов массива
x = np.count_nonzero(sr1[:,:2:] <= r[:])
print(x) # количество рецептов меньше среднего
s = np.count_nonzero(sr1)
print(s) # количество всего рецептов по массиву (100%)
percent = x*100/s
print(percent) # Ответ

[9.05523]
58803
100000
58.803


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
a = np.date[1]
a

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

оно мудреное очень))
я сначала отдельным столбцом вычислил группу
если больше 10, то плюс 1, если больше 20, то еще плюс 1
потом через hstack присобачил ее к копии массива
через unique нашел значения групп и количество в каждой
взял минимальное кол-во в группе
потом соорудил нулевой массив нужной формы и дальше его уже заполнял